<?php
// Mock Data - ข้อมูลตัวอย่างประกาศรับสมัคร TA
$positions = [
    [
        'id' => 1,
        'course_code' => 'CS101',
        'course_name' => 'Introduction to Programming',
        'professor_name' => 'ผศ.ดร. สมชาย สวัสดี',
        'job_description' => 'ช่วยจัดเตรียมสื่อการสอน ตรวจข้อมูล ติวนักศึกษา และช่วยการให้คะแนนหากจำเป็น',
        'qualifications' => 'GPA ≥ 3.0, มีความเข้าใจเกี่ยวกับ Python, สามารถสื่อสารได้ดี',
        'open_positions' => 3,
        'start_date' => '2026-09-20',
        'end_date' => '2026-10-20',
        'status' => 'open',
    ],
    [
        'id' => 2,
        'course_code' => 'MATH201',
        'course_name' => 'Calculus II',
        'professor_name' => 'รศ.ดร. วิลาวัณฑ์ นวม',
        'job_description' => 'ช่วยเตรียมสื่อการสอน บรรยายเพิ่มเติม และช่วยวิธีการแก้ปัญหา',
        'qualifications' => 'GPA ≥ 3.5, เรียนผ่านวิชา Calculus II ด้วยคะแนน A หรือ B+',
        'open_positions' => 2,
        'start_date' => '2026-09-22',
        'end_date' => '2026-10-22',
        'status' => 'open',
    ],
    [
        'id' => 3,
        'course_code' => 'ENG105',
        'course_name' => 'English Communication Skills',
        'professor_name' => 'ดร. ชมพูนุช ปรีชา',
        'job_description' => 'ช่วยให้ข้อเสนอแนะเกี่ยวกับการเขียนและการพูด ติวเตรียมสอบ',
        'qualifications' => 'GPA ≥ 3.0, TOEFL ≥ 550 หรือ IELTS ≥ 6.0, มีความเชี่ยวชาญด้านภาษาอังกฤษ',
        'open_positions' => 1,
        'start_date' => '2026-09-25',
        'end_date' => '2026-10-25',
        'status' => 'open',
    ],
    [
        'id' => 4,
        'course_code' => 'PHY150',
        'course_name' => 'Physics for Engineers',
        'professor_name' => 'ผศ. ศรัณย์ฤทธิ์ แสงสว่าง',
        'job_description' => 'ช่วยการทดลองในห้องปฏิบัติการ เตรียมอุปกรณ์ ติวแนวข้อสอบ',
        'qualifications' => 'GPA ≥ 3.2, เรียนผ่าน Physics Lab ด้วยคะแนน B+ ขึ้นไป',
        'open_positions' => 2,
        'start_date' => '2026-10-01',
        'end_date' => '2026-10-31',
        'status' => 'coming_soon',
    ],
    [
        'id' => 5,
        'course_code' => 'CHEM102',
        'course_name' => 'General Chemistry',
        'professor_name' => 'ดร. พรสวรรค์ จันทราทิพย์',
        'job_description' => 'ช่วยการทดลองเคมี การปลอดภัยในห้องปฏิบัติการ ตรวจรายงาน',
        'qualifications' => 'GPA ≥ 3.0, มีประสบการณ์ห้องปฏิบัติการเคมี ระมัดระวังและเป็นระเบียบ',
        'open_positions' => 3,
        'start_date' => '2026-09-15',
        'end_date' => '2026-10-15',
        'status' => 'closed',
    ],
    [
        'id' => 6,
        'course_code' => 'BIO201',
        'course_name' => 'Cell Biology',
        'professor_name' => 'รศ.ดร. นภา สิทธิวิทย์',
        'job_description' => 'ช่วยการสังเกตการณ์ทางจุลทรรศน์ เตรียมตัวอย่าง บรรยายสดเสริม',
        'qualifications' => 'GPA ≥ 3.0, มีความรู้ด้านชีววิทยาเซลล์ สามารถใช้จุลทรรศน์ได้',
        'open_positions' => 1,
        'start_date' => '2026-09-10',
        'end_date' => '2026-09-30',
        'status' => 'closed',
    ],
];

// Return positions data to view
return view('pages.positions.index', compact('positions'));
?>
